### ISSUE TITLE
chapter10/camel-cxf-rest-spring-boot on minishift 

### ISSUE THREAD

**Issue by imranrazakhan** [camelinaction/camelinaction2#67]
Hi,
I tried to run chapter10-camel-cxf-rest-spring-boot example on minishift, it was successfully deployed using fabric8 plugin with NodePort type.

```
<configuration>
					<enricher>
						<config>
							<fmp-service>
								<type>NodePort</type>
							</fmp-service>
						</config>
					</enricher>
				</configuration>
```

I change route like 

from("cxfrs:http://0.0.0.0:9191?resourceClasses=camelinaction.RestOrderService&bindingStyle=SimpleConsumer&providers=#jsonProvider")

But I am unable to access API out of cluster. though its working fine when i CURL it from minishift console terminal option.

How we can access it out of cluster and map NODEPORT like 30055 --> 9191?

C:\mycluster>oc get routes

Above command gives following URL, but its not accessible from it too.

******-minishift.192.168.99.101.nip.io

Regards,

**Comment by davsclaus** [comment]
Chapter 10 is not covering minishift. Please use another forum to discuss this, as we want to keep this github repo about the source code for the book only, and about the content in that book.

**Comment by davsclaus** [comment]
You can for example ask on @fabric8 community as the fmp plugin is from there
https://fabric8.io/community/index.html

**Comment by davsclaus** [comment]
And check the fmp documentation
https://maven.fabric8.io/

And in the `service.yml` file you can setup service configuration such as port mappings
https://github.com/davsclaus/fabric8-hello/blob/master/helloswarm/src/main/fabric8/service.yml

As its just standard k8s you can then add the spec for the port mappings etc.
```
 spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      project: helloswarm-kubernetes
      provider: fabric8
      group: com.camelinaction
    type: NodePort
```

A good trick is too look in the target/classes/META-INF/fabric8 folder and find the generated files where you can then copy/paste from them, and adjust in the `service.yml` file.
